# Generated by Django 4.2.16 on 2026-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_cart_category_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal_discount_percent',
            field=models.IntegerField(blank=True, default=0, help_text='Optional override percentage', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.9, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, default=38),
        ),
    ]
