# Generated by Django 4.2.16 on 2026-08-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_product_deal_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct online image URL (Unsplash, CDN, etc.)', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
